version: '3'
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
    - 5432:5432
    volumes:
    - ./.postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  cache:
    image: redis:7.2.0-alpine
    restart: always
    ports:
    - 6379:6379
    command: >
      --requirepass P@ssw0rd
  web:
    build: .
    restart: always
    ports:
    - "5000:5000"
    volumes:
    - "./and_platform/.adce_data:/opt/app/and_platform/.adce_data"
    depends_on:
    - db
    - cache
  checker:
    build: .
    restart: always
    command: checker
    volumes:
    - "./and_platform/.adce_data:/opt/app/and_platform/.adce_data"
    depends_on:
    - db
    - cache
  # sample_server:
  #   privileged: true
  #   build:
  #     dockerfile: sample_server.Dockerfile
  #   ports:
  #   - 22022:22
  
