Parameters:
  EventSlug:
    Type: String
    Default: Ailurus
    Description: A friendly environment name that will be used for namespacing all
      cluster resources.
  TeamId:
    Type: String
    Default: '1'
    Description: Team ID to identify team resources as a string.
  MachineAMI1:
    Type: String
    Default: ami-0afd0b2f1ea7e2974
    Description: The AMI ID for CTF challenge machine that will be created using EC2.
  MachineAMI2:
    Type: String
    Default: ami-086171d571328abeb
    Description: The AMI ID for CTF challenge machine that will be created using EC2.
  MachinePrivateIpAddress:
    Type: String
    Default: 10.0.1.1
    Description: Assigned internal IP address. Be cautious, must assigned uniquely
      per instance.
  MachineType:
    Type: String
    Default: c5a.large
    Description: Machine type name for EC2.
  MachineSecurityGroupId:
    Type: String
    Description: Security group ID created before for all teams instances.
  MachineSubnetId:
    Type: String
    Description: Subnet ID created before for all teams instances.
  PublicKey:
    Type: String
    Default: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICfp1F7DhdWZdqkYaUGCZcBsLmJeu9izpIyGpmmg7eCz example
    Description: Predefined SSH public key that will be installed in teams machine.
Resources:
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Join
        - ''
        - - KeyPair
          - !Ref EventSlug
          - !Ref TeamId
      PublicKeyMaterial: !Ref PublicKey
      Tags:
        - Key: ManagedBy
          Value: !Ref EventSlug
  Ec2Instance:
    Type: AWS::EC2::Instance
    UpdateReplacePolicy: "Delete"
    DeletionPolicy: "Delete"
    Properties:
      ImageId: !Ref MachineAMI1
      KeyName: !Ref KeyPair
      InstanceType: !Ref MachineType
      PrivateIpAddress: !Ref MachinePrivateIpAddress
      SecurityGroupIds:
        - !Ref MachineSecurityGroupId
      SubnetId: !Ref MachineSubnetId
      Tags:
        - Key: ManagedBy
          Value: !Ref EventSlug
      UserData: !Base64 |
          #!/bin/bash
          useradd -m -g sudo ctf
          mkdir -p /home/ctf/.ssh
          echo "{{Ailurus.CheckerPublicKey}}" >> /home/ctf/.ssh/authorized_keys
Outputs:
  MachineInstanceId:
    Value: !Ref Ec2Instance
    Description: Instance ID of the EC2 instance
  MachinePrivateIp:
    Value: !GetAtt Ec2Instance.PrivateIp
    Description: Private IP address of the EC2 instance