- name: Combine configuration files
  assemble:
    src: /etc/wireguard
    dest: /etc/wireguard/peer.conf
    regexp: "\\S*.peer.conf"

- shell: cat /etc/wireguard/wg0.back.conf > /etc/wireguard/wg0.conf
- shell: cat /etc/wireguard/peer.conf >> /etc/wireguard/wg0.conf
